# this is an example telebot docker-compose file
version: '3'
services:

  db:
    image: postgres:latest
    container_name: telebot_database
    environment:
      - POSTGRES_PASSWORD=somepassword
    restart: always

  smlr:
    image: finnetrolle/telebot:latest
    container_name: telebot_app
    restart: always
    environment:
      # database connection
      SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME=postgres
      SPRING_DATASOURCE_PASSWORD=somepassword

      # telegram bot settings
      TELEGRAM_BOT_TOKEN=enter_here_your_telegram_token
      TELEGRAM_BOT_USERNAME=enter_here_your_bot_name
      TELEGRAM_BOT_ALIVE=TRUE

      # secrets
      API_SECRET_CAST_GROUP=secret
      API_SECRET_CAST_GLOBAL=secret
      API_SECRET_UTILS=secret

      # superuser
      TELEBOT_SUPERUSER=Your character Name

      # Only for xXDEATHXx register system
      TELEBOT_SECRET_EXTERNAL_REGISTER=secret
      TELEBOT_EXTERNAL_GROUPS_SECRET=secret
      TELEBOT_EXTERNAL_GROUPS_URL=secret

      #mailbot
      MAILBOT_KEY_ID=your key id for mail
      MAILBOT_VCODE=your vcode for mail
      MAILBOT_LIST_ID=your mailing list id
      MAILBOT_ALIVE=false

      YANDEX_KEY=secret

      SERVER_PORT=8080

    links:
      - db
    ports:
      - "8080:8080"
    depends_on:
      - db